version: "3.2"

services:
  postgres:
    image: postgres:14.5
    hostname: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "yes"
      POSTGRES_DB: "rstudio"
    volumes:
      - var_lib_postgres:/var/lib/postgres
    expose:
      - "5432"
 
  mysql1:
    image: mysql:5.7
    hostname: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql1:/var/lib/mysql



  slurmdbd1:
    image: mmayer123/slurm-docker-cluster:${PWB_VERSION:-2025.09.1-401.pro2}-slurm-${SLURM_VERSION1:-24.11.6-1}-${DIST:-jammy}
    build:
      context: .
      dockerfile: Dockerfile.compile.multi
      args:
        SLURM_VERSION: ${SLURM_VERSION1:-24.11.6-1}
        DIST: ${DIST:-jammy}
        DISTNUM: ${DISTNUM:-2204}
        CLUSTER: 1
        PWB_VERSION: ${PWB_VERSION:-2025.09.1-401.pro2}
    command: ["slurmdbd"]
    hostname: slurmdbd1
    volumes:
      - etc_munge1:/etc/munge1
      - etc_slurm1:/opt/slurm/1/etc
    expose:
      - "6819"
      - "22"
    depends_on:
      - mysql1

  slurmctld1:
    image: mmayer123/slurm-docker-cluster:${PWB_VERSION:-2025.09.1-401.pro2}-slurm-${SLURM_VERSION1:-24.11.6-1}-${DIST:-jammy}
    build:
      context: .
      dockerfile: Dockerfile.compile.multi
      args:
        SLURM_VERSION: ${SLURM_VERSION1:-24.11.6-1}
        DIST: ${DIST:-jammy}
        DISTNUM: ${DISTNUM:-2204}
        CLUSTER: 1
        PWB_VERSION: ${PWB_VERSION:-2025.09.1-401.pro2}
    command: ["slurmctld"]
    hostname: slurmctld1
    privileged: true 
    volumes:
      - etc_munge1:/etc/munge1
      - etc_slurm1:/opt/slurm/1/etc
      - home:/home
    expose:
      - "6817"
      - "22"
    depends_on:
      - "slurmdbd1"


  c11:
    image: mmayer123/slurm-docker-cluster:${PWB_VERSION:-2025.09.1-401.pro2}-slurm-${SLURM_VERSION1:-24.11.6-1}-${DIST:-jammy}
    build:
      context: .
      dockerfile: Dockerfile.compile.multi
      args:
        SLURM_VERSION: ${SLURM_VERSION1:-24.11.6-1}
        DIST: ${DIST:-jammy}
        DISTNUM: ${DISTNUM:-2204}
        CLUSTER: 1
        PWB_VERSION: ${PWB_VERSION:-2025.09.1-401.pro2}
    command: ["slurmd"]
    hostname: c11
    privileged: true
    volumes:
      - etc_munge1:/etc/munge1
      - etc_slurm1:/opt/slurm/1/etc
      - home:/home
    expose:
      - "6818"
      - "22"
    depends_on:
      - "slurmctld1"

  c12:
    image: mmayer123/slurm-docker-cluster:${PWB_VERSION:-2025.09.1-401.pro2}-slurm-${SLURM_VERSION1:-24.11.6-1}-${DIST:-jammy}
    build:
      context: .
      dockerfile: Dockerfile.compile.multi
      args:
        SLURM_VERSION: ${SLURM_VERSION1:-24.11.6-1}
        DIST: ${DIST:-jammy}
        DISTNUM: ${DISTNUM:-2204}
        CLUSTER: 1
        PWB_VERSION: ${PWB_VERSION:-2025.09.1-401.pro2}
    command: ["slurmd"]
    hostname: c12
    privileged: true
    volumes:
      - etc_munge1:/etc/munge1
      - etc_slurm1:/opt/slurm/1/etc
      - home:/home
    expose:
      - "6818"
      - "22"
    depends_on:
      - "slurmctld1"


  mysql2:
    image: mysql:5.7
    hostname: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql2:/var/lib/mysql



  slurmdbd2:
    image: mmayer123/slurm-docker-cluster:${PWB_VERSION:-2025.09.1-401.pro2}-slurm-${SLURM_VERSION2:-23.11.11-1}-${DIST:-jammy}
    build:
      context: .
      dockerfile: Dockerfile.compile.multi
      args:
        SLURM_VERSION: ${SLURM_VERSION2:-23.11.11-1}
        DIST: ${DIST:-jammy}
        DISTNUM: ${DISTNUM:-2204}
        CLUSTER: 2
        PWB_VERSION: ${PWB_VERSION:-2025.09.1-401.pro2}
    command: ["slurmdbd"]
    hostname: slurmdbd2
    volumes:
      - etc_munge2:/etc/munge2
      - etc_slurm2:/opt/slurm/2/etc
    expose:
      - "6819"
      - "22"
    depends_on:
      - mysql2

  slurmctld2:
    image: mmayer123/slurm-docker-cluster:${PWB_VERSION:-2025.09.1-401.pro2}-slurm-${SLURM_VERSION2:-23.11.11-1}-${DIST:-jammy}
    build:
      context: .
      dockerfile: Dockerfile.compile.multi
      args:
        SLURM_VERSION: ${SLURM_VERSION2:-23.11.11-1}
        DIST: ${DIST:-jammy}
        DISTNUM: ${DISTNUM:-2204}
        CLUSTER: 2
        PWB_VERSION: ${PWB_VERSION:-2025.09.1-401.pro2}
    command: ["slurmctld"]
    hostname: slurmctld2
    privileged: true 
    volumes:
      - etc_munge2:/etc/munge2
      - etc_slurm2:/opt/slurm/2/etc
      - home:/home
    expose:
      - "6817"
      - "22"
    depends_on:
      - "slurmdbd2"


  c21:
    image: mmayer123/slurm-docker-cluster:${PWB_VERSION:-2025.09.1-401.pro2}-slurm-${SLURM_VERSION2:-23.11.11-1}-${DIST:-jammy}
    build:
      context: .
      dockerfile: Dockerfile.compile.multi
      args:
        SLURM_VERSION: ${SLURM_VERSION2:-23.11.11-1}
        DIST: ${DIST:-jammy}
        DISTNUM: ${DISTNUM:-2204}
        CLUSTER: 2
        PWB_VERSION: ${PWB_VERSION:-2025.09.1-401.pro2}
    command: ["slurmd"]
    hostname: c21
    privileged: true
    volumes:
      - etc_munge2:/etc/munge2
      - etc_slurm2:/opt/slurm/2/etc
      - home:/home
    expose:
      - "6818"
      - "22"
    depends_on:
      - "slurmctld2"

  c22:
    image: mmayer123/slurm-docker-cluster:${PWB_VERSION:-2025.09.1-401.pro2}-slurm-${SLURM_VERSION2:-23.11.11-1}-${DIST:-jammy}
    build:
      context: .
      dockerfile: Dockerfile.compile.multi
      args:
        SLURM_VERSION: ${SLURM_VERSION2:-23.11.11-1}
        DIST: ${DIST:-jammy}
        DISTNUM: ${DISTNUM:-2204}
        CLUSTER: 2
        PWB_VERSION: ${PWB_VERSION:-2025.09.1-401.pro2}
    command: ["slurmd"]
    hostname: c22
    privileged: true
    volumes:
      - etc_munge2:/etc/munge2
      - etc_slurm2:/opt/slurm/2/etc
      - home:/home
    expose:
      - "6818"
      - "22"
    depends_on:
      - "slurmctld2"


  rstudio:
    image: mmayer123/slurm-docker-cluster:${PWB_VERSION:-2025.09.1-401.pro2}-slurm-${SLURM_VERSION1:-24.11.6-1}-${SLURM_VERSION2:-23.11.11-1}-${DIST:-jammy}
    build:
      context: .
      dockerfile: Dockerfile.compile.multi.rstudio
      args:
        SLURM_VERSION1: ${SLURM_VERSION1:-24.11.6-1}
        SLURM_VERSION2: ${SLURM_VERSION2:-23.11.11-1}
        DIST: ${DIST:-jammy}
        DISTNUM: ${DISTNUM:-2204}
        PWB_VERSION: ${PWB_VERSION:-2025.09.1-401.pro2}
    command: ["rstudio"]
    hostname: rstudio
    privileged: true
    volumes:
      - etc_munge1:/etc/munge1
      - etc_munge2:/etc/munge2
      - etc_slurm1:/opt/slurm/1/etc
      - etc_slurm2:/opt/slurm/2/etc
      - home:/home
    expose:
      - "6818"
      - "8787"
      - "22"
    ports:
      - "8888:8787"
    environment:
      RSP_LICENSE: ${RSP_LICENSE}
    depends_on:
      - "c11"
      - "c12" 
      - "c21"
      - "c22"
      - "postgres"



volumes:
  etc_munge1:
  etc_slurm1:
  slurm_jobdir1:
  var_lib_mysql1:
  etc_munge2:
  etc_slurm2:
  slurm_jobdir2:
  var_lib_mysql2:
  home:
  var_lib_postgres:
