# Enable debugging
enable-debug-logging=1

# Basic configuration
slurm-service-user=slurm
slurm-bin-path=/opt/slurm/2/bin

# User/group and resource profiles
profile-config=/etc/rstudio/launcher.cluster2.profiles.conf
resource-profile-config=/etc/rstudio/launcher.cluster2.resources.conf